apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vxj8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vxj8
    app.kubernetes.io/part-of: ci10t-786-0020-app
  name: devfile-sample-vxj8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vxj8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vxj8
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0020-tenant/ci10t-786-0020-app/devfile-sample-vxj8@sha256:0e4b0457b225352362d431272cb1d2da148348ba6a9756b2fa4effdea4737a72
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
